### ISSUE TITLE
Bra

### ISSUE THREAD

**Issue by SkyBouncer** [Lekesoldat/owe-backend#1]
Hvordan får man kjøpt aksjer i dette?

**Comment by fshauge** [comment]
+1

**Comment by Lekesoldat** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/8e3b2faa-7e4d-4458-b8c8-69353e0c7038-c4b194b3-5f90-4226-aa28-58a15689950e-v1.png?transparent=1&palette=1&width=246)
